// This array must contain the list of all the rive to include.

const riveList = [
"amis.rive",
"animaux.rive",
"arts.rive",
"automobiles.rive",
"betise.rive",
"cinema.rive",
"college.rive",
"defauts.rive",
"ecologie.rive",
"famille.rive",
"foot.rive",
"futur.rive",
"gouts.rive",
"internet.rive",
"jeuxvideos.rive",
"marques.rive",
"musique.rive",
"nourriture.rive",
"origines.rive",
"passion.rive",
"phobies.rive",
"presentation.rive",
"robots.rive",
"salutations.rive",
"savie.rive",
"special.rive",
"sport.rive",
"voyages.rive",
"loisirs.rive",
];