// This array must contain the list of all the rive to include.

const riveList = [
"brain/amis.rive",
"brain/animaux.rive",
"brain/arts.rive",
"brain/automobiles.rive",
"brain/betise.rive",
"brain/cinema.rive",
"brain/college.rive",
"brain/defauts.rive",
"brain/ecologie.rive",
"brain/famille.rive",
"brain/foot.rive",
"brain/futur.rive",
"brain/gouts.rive",
"brain/internet.rive",
"brain/jeuxvideos.rive",
"brain/marques.rive",
"brain/musique.rive",
"brain/nourriture.rive",
"brain/origines.rive",
"brain/passion.rive",
"brain/phobies.rive",
"brain/presentation.rive",
"brain/robots.rive",
"brain/salutations.rive",
"brain/savie.rive",
"brain/special.rive",
"brain/sport.rive",
"brain/voyages.rive",
"brain/loisirs.rive",
];